id: opecha:P009485
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016941
  title: འཕགས་པ་ཐུགས་རྗེ་ཆེན་པོའི་སྒྲུབ་ཐབས་ཀྱི་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་རིན་ཆེན་འཕྲེང་བ་དང་པོ་བསྟོད་འགྲེལ་པ་དོན་གསལ་སྣང་བ་བཅས
  volume: ''
  author: ''
