id: P009485
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00EGS1016941
  title: འཕགས་པ་ཐུགས་རྗེ་ཆེན་པོའི་སྒྲུབ་ཐབས་ཀྱི་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་རིན་ཆེན་འཕྲེང་བ་དང་པོ་བསྟོད་འགྲེལ་པ་དོན་གསལ་སྣང་བ་བཅས
  author: ''
  volumes:
    248ba76f20a74a2f93e84b8d9b9c7da8:
      image_group_id: I01JW221
      title: ''
      volume_number: 1
      total_pages: 164
      base_file: v001.txt
