id: IFC18DAA1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:56:28+00:00'
last_modified: '2022-06-08T11:22:06.693892+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016941
  title: འཕགས་པ་ཐུགས་རྗེ་ཆེན་པོའི་སྒྲུབ་ཐབས་ཀྱི་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་རིན་ཆེན་འཕྲེང་བ་དང་པོ་བསྟོད་འགྲེལ་པ་དོན་གསལ་སྣང་བ་བཅས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1606':
      image_group_id: I01JW221
      title: ''
      total_pages: 164
      order: 1
      base_file: 1606.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
